// Generated by CoffeeScript 1.7.1
(function() {
  var route;

  route = require('./route');

  route.map({
    method: 'get',
    url: /^\/hello\/$/i,
    controller: 'Index',
    action: 'index'
  });

  exports.staticFileDir = 'static';

}).call(this);
