// Generated by CoffeeScript 1.7.1
(function() {
  var parseURL, routes;

  parseURL = require('url').parse;

  routes = {
    get: [],
    post: [],
    head: [],
    put: [],
    "delete": []
  };

  exports.map = function(dict) {
    var method;
    if ((dict != null) && (dict.url != null) && (dict.controller != null)) {
      method = dict.method != null ? dict.method.toLowerCase() : 'get';
      routes[method].push({
        u: dict.url,
        c: dict.controller,
        a: dict.action || 'index'
      });
    }
  };

  exports.getActionInfo = function(url, method) {
    var m_route, m_routes, pathname, r, _i, _len;
    r = {
      controller: null,
      action: null,
      args: null
    };
    method = method != null ? method.toLowerCase() : 'get';
    pathname = parseURL(url).pathname;
    m_routes = routes[method];
    for (_i = 0, _len = m_routes.length; _i < _len; _i++) {
      m_route = m_routes[_i];
      r.args = m_route.u.exec(pathname);
      if (r.args != null) {
        r.controller = m_route.c;
        r.action = m_route.a;
        r.args.shift();
        break;
      }
    }
    return r;
  };

}).call(this);
