// Generated by CoffeeScript 1.7.1

/*
@author zxy
@email zhaoxingyu19920404@gmail.com
 */

(function() {
  var coffeeServer;

  coffeeServer = require('./server');

  coffeeServer.runServer(8080);

}).call(this);
